<?php

namespace App\Models\Backoffice;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Tymon\JWTAuth\Contracts\JWTSubject;
use Illuminate\Database\Eloquent\Relations;
/**
 * This is User Model
 *
 * Class User
 * @package App\Http\Models
 */


/**
 * @SWG\Definition(
 *   type="object",
 *   @SWG\Xml(
 *     name="UserModel"
 *   ),
 *   @SWG\Property(
 *      property="id",
 *      type="integer",
 *      description="Первичный ключ",
 *      default="available"
 *   ),
 *   @SWG\Property(
 *      property="first_name",
 *      type="boolean",
 *      description="Имя. Максимально 50 символов.",
 *      default="available"
 *   ),
 *   @SWG\Property(
 *      property="last_name",
 *      type="string",
 *      description="Фамилия. Максимально 50 символов.",
 *      default="available"
 *   ),
 *   @SWG\Property(
 *      property="skype_id",
 *      type="string",
 *      description="Skype ID. Поле необязательное, может быть до 50 символов.",
 *      default="available"
 *   ),
 *   @SWG\Property(
 *      property="telegram_id",
 *      type="string",
 *      description="Telegram ID. Поле необязательное, может быть до 50 символов.",
 *      default="available"
 *   ),
 *   @SWG\Property(
 *      property="email",
 *      type="string",
 *      description="Email. Максимально 50 символов.",
 *      default="available"
 *   ),
 *   @SWG\Property(
 *      property="password",
 *      type="string",
 *      description="Пароль. 30 символов максимум.",
 *      default="available"
 *   ),
 *   @SWG\Property(
 *      property="password_repeat",
 *      type="string",
 *      description="Повтор пароля",
 *      default="available"
 *   ),
 *   @SWG\Property(
 *      property="secret_question_id",
 *      type="string",
 *      description="ID секретного вопроса",
 *      default="available"
 *   ),
 *   @SWG\Property(
 *      property="secret_question_answer",
 *      type="string",
 *      description="Ответ на секретный вопрос. От 5 до 255 символов.",
 *      default="available"
 *   ),
 *   @SWG\Property(
 *      property="role",
 *      type="integer",
 *      description="Роль пользователя. Может принимать значения, определённые методом /api/v1/role.",
 *      default="available"
 *   ),
 * )
 */


class User extends Authenticatable implements JWTSubject
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name', 'email', 'password', 'skype_id', 'telegram_id', 'api_key', 'id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token', 'permissions', 'created_at', 'updated_at'
    ];

    /**
     * @var Role[]
     */
    // protected $roles;

    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    public function getJWTCustomClaims() : array
    {
        return [];
    }

    public function getTable() : string
    {
        return 'users'; // TODO: Change the autogenerated stub
    }

    /**
     * Get all advertisements for this user
     * @return Relations\HasMany
     */
    public function adv() : Relations\HasMany
    {
        return $this->hasMany(Adv::class);
    }

    /**
     * Has only one bill
     * @return Relations\HasOne
     */
    public function bill() : Relations\HasOne
    {
        return $this->hasOne(Bill::class, 'user_id', 'id');
    }

    /**
     * Has many roles
     * @return Relations\BelongsToMany
     */
    public function roles(): Relations\BelongsToMany
    {
        return $this->belongsToMany(Role::class, 'role_users', 'role_id', 'user_id');
    }

    /**
     * Has access or not
     * @param string rule
     * @return int
     */
    public function hasAccess($rule): int
    {
        if ($this->roles !== null) {
            foreach($this->roles as $role) {
                foreach($role->permissions as $permission => $value) {
                    if($permission === $rule) {
                        return $value;
                    }
                }
            }
        }

        // Rule not found
        return false;
    }
}
